import type { ResumUsDto } from "./services/analisi";
import type { ReservaDto } from "./services/reserves";

export function resumExemple(): ResumUsDto {
  return {
    starts_at: "2026-08-31T22:00:00Z",
    ends_at: "2026-09-30T22:00:00Z",
    confirmed_count: 18,
    cancelled_count: 3,
    reserved_hours: 42,
    available_hours: 160,
    occupancy_ratio: 42 / 160,
    average_attendance: 22,
    unregistered_count: 2,
    below_min_attendance: true,
    spaces: [
      {
        space_id: "ex-sala",
        space_name: "Sala gran",
        capacity: 80,
        min_attendance: 20,
        confirmed_count: 8,
        cancelled_count: 1,
        reserved_hours: 18,
        available_hours: 40,
        occupancy_ratio: 18 / 40,
        average_attendance: 36,
        unregistered_count: 0,
        below_min_attendance: false,
      },
      {
        space_id: "ex-assaig",
        space_name: "Sala d’assaig",
        capacity: 25,
        min_attendance: 8,
        confirmed_count: 6,
        cancelled_count: 1,
        reserved_hours: 14,
        available_hours: 40,
        occupancy_ratio: 14 / 40,
        average_attendance: 12,
        unregistered_count: 1,
        below_min_attendance: false,
      },
      {
        space_id: "ex-taller",
        space_name: "Taller",
        capacity: 16,
        min_attendance: 10,
        confirmed_count: 3,
        cancelled_count: 1,
        reserved_hours: 6,
        available_hours: 40,
        occupancy_ratio: 6 / 40,
        average_attendance: 7,
        unregistered_count: 1,
        below_min_attendance: true,
      },
      {
        space_id: "ex-pati",
        space_name: "Pati cobert",
        capacity: 50,
        min_attendance: null,
        confirmed_count: 1,
        cancelled_count: 0,
        reserved_hours: 4,
        available_hours: 40,
        occupancy_ratio: 4 / 40,
        average_attendance: 28,
        unregistered_count: 0,
        below_min_attendance: false,
      },
    ],
  };
}

export function reservesExemple(): ReservaDto[] {
  return [
    {
      id: "ex-r1",
      space_id: "ex-sala",
      space_name: "Sala gran",
      starts_at: "2026-09-10T16:00:00Z",
      ends_at: "2026-09-10T18:00:00Z",
      status: "confirmed",
      mine: false,
      coordinator_name: "Carla Puig",
      attendance_count: 40,
      capacity: 80,
      min_attendance: 20,
      exceeds_capacity: false,
      below_min_attendance: false,
    },
    {
      id: "ex-r2",
      space_id: "ex-assaig",
      space_name: "Sala d’assaig",
      starts_at: "2026-09-12T09:00:00Z",
      ends_at: "2026-09-12T11:00:00Z",
      status: "confirmed",
      mine: false,
      coordinator_name: "Marc Soler",
      attendance_count: null,
      capacity: 25,
      min_attendance: 8,
      exceeds_capacity: false,
      below_min_attendance: false,
    },
    {
      id: "ex-r3",
      space_id: "ex-taller",
      space_name: "Taller",
      starts_at: "2026-09-14T17:00:00Z",
      ends_at: "2026-09-14T19:00:00Z",
      status: "cancelled",
      mine: false,
      coordinator_name: "Carla Puig",
      attendance_count: 7,
      capacity: 16,
      min_attendance: 10,
      exceeds_capacity: false,
      below_min_attendance: true,
    },
  ];
}
